server:
  port: 2601

logging:
  path: logs/
  level:
    root: INFO

spring:
  profiles.active: mysql
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      jadira.usertype.autoRegisterUserTypes: true
      jadira.usertype.databaseZone: jvm
      jadira.usertype.javaZone: jvm
    hibernate:
      naming:
        implicit-strategy: org.minjay.gamers.accounts.data.jpa.CustomImplicitNamingStrategy
      ddl-auto: update
      use-new-id-generator-mappings: false
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.163.com
    username: minjay26@163.com
    password: lz060213
    default-encoding: UTF-8
    port: 25

email:
  template:
    bindEmail: 您本次操作的验证码为:<b>code<b>
    modifyPassword: 您正在申请修改密码,验证码为:<b>code<b>

qcloud:
  appId: 1259754305
  secretId: AKIDHJ9nIfjvrcBZq2HThjZDf4NVEl9NOpaF
  secretKey: dkkZ7dLsHORJ0ALajDZkgpsVH2SDpeMu
  bucket: gamers-1259754305
  domain: https://gamers-1259754305.cos.ap-shanghai.myqcloud.com

---
spring:
  profiles: mysql
  datasource:
    driver-class-name: ${datasource.driver-class-name:com.mysql.jdbc.Driver}
    url: ${datasource.url:jdbc:mysql://localhost:3306/gamers_accounts?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai}
    username: ${datasource.username:root}
    password: ${datasource.password:111111}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
